- name: standard python system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python
    - python-dev
    - python-pip
  sudo: yes

- name: bootstrap pip and virtualenv
  pip: name={{ item }} state=present
  with_items:
    - pip
    - virtualenv
  sudo: yes

- name: install requirements.txt
  pip: requirements={{ requirements_path }} virtualenv={{ virtualenv_dir }}
  sudo: yes

- name: source virtualenv in .bashrc
  lineinfile: dest={{ home_dir }}.bashrc line="{{ item }}"
  with_items:
    - source {{ virtualenv_dir }}/bin/activate
    - cd {{ shared_dir }}{{ project_name }}/
