- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: upgrade the distro
  apt: upgrade=yes
  sudo: yes

- name: install basic packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp
    - ssh
    - curl
    - wget
    - vim
    - git
  sudo: yes
